### ISSUE TITLE
why sometime getView() will throw exception?? can you explain it?

### ISSUE THREAD

**Issue by JackyAndroid** [tinmegali/tutsplus_sample-mvp#1]
why sometime getView() will throw exception?? can you explain it?

``` java
@Override
public Context getActivityContext() {
        try {
            return getView().getActivityContext();
        } catch (NullPointerException e) {
            return null;
        }
    }
```

**Comment by tinmegali** [comment]
Hello @JackyAndroid 
Since <code>mView</code> is a <code>WeakReference<></code> it can be nullified by the system. Theoretically this won't occur on this application, since the <code>mView</code> is populated with a View reference every time after configuration changes occurred. Although I believe that the code should consider this possibility and prepare itself for it, hence my decision to throw an <code>NullPointerException</code>. 

```
protected MVP_Main.RequiredViewOps getView() throws NullPointerException{
        if ( mView != null )
            return mView.get();
        else
            throw new NullPointerException("View is unavailable");
    }
```

Imagine a scenario where the app does some kind of long running task on a Background Thread that'll return some feedback to the View and imagine that the user don't wait to the result and goes to other Activity. The <code>getView()</code> would return an invalid result, since the original Activity would be destroyed and it would be impossible to return any feedback to it after the task was concluded.
I believe that the obligatory check for <code>NullPointerException</code> just makes the code be more prepared for such eventualities.
